config/routes.rb
LikeCounter::Application.routes.draw do
  get "static_pages/about"
  match "/about", to: "static_pages#about"
  get "static_pages/contact"
  match "/contact", to: "static_pages#contact"
  get "static_pages/help"
  match "/help", to: "static_pages#help"
  get "static_pages/home"
  match "whats_this", to: "static_pages#whats_this"
  get "static_pages/whats_this"

  resources :sessions, only: [:new, :create, :destroy]

  resources :emails, only: [:create, :destroy, :index, :show] 

  resources :users do
    resources :emails, only: [:create, :destroy, :index, :show]
    member do
      put 'likes'
      post 'email_likes'
    end
    collection do
    end
  end

  root to: 'users#like_page'
  match '/like', to: 'users#like_page', via: [:get, :post]

  match '/signout', to: 'sessions#destroy', via: :delete

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end

  def help
  end
  
  def home
  end

  def whats_this
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.haml
- provide(:title, "About WorthReading")
%h1 About WorthReading
%p To be filled in....

app/views/static_pages/contact.html.haml
- provide(:title, "Contact Us")
%h1 Contact Us
%p We can be reached at... 

app/views/static_pages/help.html.haml
- provide(:title, "Help")
%h1 Help
%p To be filled in...

app/views/static_pages/home.html.haml
%h1 Home

app/views/static_pages/whats_this.html.haml
.row
  .span6.offset3
    %h1 What's this?
.row
  .span8.offset2
    .hero-unit
      %p 
        The sender of this message inserted that button at the end of his/her 
        message so that you could volunteer a dollop of positive feedback if 
        you found the message worth reading. These signals can be used to decide 
        whether to send similar messages to you in the future.
        
      %br/
      %br/
      %p When you send the same message to several people would you like to:
      %ul
        %li 
          %p send individual messages to each of them?
        %li 
          %p discover when they open the message?
        %li 
          %p discover if they like the message? 
      %br
      %p
        If so, sign up 
        = link_to "here.", new_session_path