config/routes.rb
LikeCounter::Application.routes.draw do
  get "static_pages/about"
  match "/about", to: "static_pages#about"
  get "static_pages/contact"
  match "/contact", to: "static_pages#contact"
  get "static_pages/help"
  match "/help", to: "static_pages#help"
  get "static_pages/home"
  match "whats_this", to: "static_pages#whats_this"
  get "static_pages/whats_this"

  resources :sessions, only: [:new, :create, :destroy]

  resources :emails, only: [:create, :destroy, :index, :show] 

  resources :users do
    resources :emails, only: [:create, :destroy, :index, :show]
    member do
      put 'likes'
      post 'email_likes'
    end
    collection do
    end
  end

  root to: 'users#like_page'
  match '/like', to: 'users#like_page', via: [:get, :post]

  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email_address   :string(255)
#  likes           :integer          default(50)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :email_address, :name, :likes, :password, :password_confirmation
  has_secure_password
  has_many :emails
  
  before_save { |user| user.email_address = email_address.downcase }
  before_save :create_remember_token

  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email_address, presence:   true,
    format:     { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  validates :password, presence: true, on: :create
  validates :password_confirmation, presence: true, on: :create


  def self.incr_decr_likes(liked_user, user_who_likes)
      liked_user.increment!(:likes, 5)
      user_who_likes.decrement!(:likes, 5)
      liked_user.save!
      user_who_likes.save!
  end

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#  before_filter :signed_in, only: [:index, :edit, :show]
  # GET /users
  # GET /users.json
  def index

    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @emails = @user.emails

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to @user, success: 'Welcome to your profile page.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        sign_in @user
        format.html { redirect_to @user, 
          flash: { success: 'Your account information was successfully updated.' }
        }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  # This page displays the users with their number of likes 
  def like_page
    @users = User.all order: 'likes DESC'
  end

  def email_likes
    if params[:email_address]
      # Determines whether the user who likes is in database or not
      # If the user is not in database, we simply create a user
      user_who_likes = User.find_by_email(params[:who_likes]) ? 
        User.find_by_email_address(params[:who_likes]) :
        User.create(email_address: params[:who_likes], 
                    name: 'stub_name',
                    password: "#{params[:who_likes]}",
                    password_confirmation: "#{params[:who_likes]}"
                   )
      liked_user = User.find_by_id(params[:id])
      User.incr_decr_likes(liked_user, user_who_likes)
      success_msg = "Thanks for liking.  Feel free to close the window if you'd like"
      redirect_to root_path, flash: { success: success_msg } 
    else
      redirect_to root_path, flash: { error: 'Invalid request' }
    end
  end

  # This method increments a user's likes by 5
  def likes
    if signed_in? 
      liked_user = User.find_by_id!(params[:id])
      user_who_likes = current_user
      User.incr_decr_likes(liked_user, user_who_likes)
      sign_in user_who_likes
      redirect_to root_path 
    else
      redirect_to new_session_path, flash: { notice: 'Hey, we need to know who you are first' }
    end
  end


  private

  def signed_in
    redirect_to new_session_path, notice: 'Gotta sign in to do that' unless signed_in?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
.row
  .span4.offset4
    = form_for @user do |f|
      = render 'shared/error_messages'

      .field
        = f.label :name
        = f.text_field :name
      .field
        = f.label :email_address
        = f.text_field :email_address
      .field
        = f.label :password
        = f.password_field :password
      .field
        = f.label :password_confirmation, "Confirm Password"
        = f.password_field :password_confirmation
      .actions
        - if current_user
          = f.submit 'Submit Changes'
        - else
          = f.submit 'Sign up'

app/views/users/edit.html.haml
.row 
  .span5.offset3
    %h2 Edit Account Information 

= render 'form'

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Name
    %th Email
    %th Likes
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.email_address
      %td= user.likes
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New User', new_user_path
|
= link_to 'Home', root_path

app/views/users/like.html.haml
%h1 Like him if you want 

%table
  %tr
    %th Name
    %th Likes

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.likes
      %td= button_to 'Like me'

app/views/users/like_page.html.haml
- provide(:title, "Welcome to WorthReading. Sign/Sign Up to get started")
%br/
%br/ 

.row
  -unless signed_in?
    .span8
      .hero-unit
        %p
          When you send the same message to several people would you like to:
          %ul
            %li send individual messages to each of them?
            %li discover when they open the message?
            %li discover if they like the message? 
          Then sign up for WorthReading which can give you these features
          %br/
        %p.center
          = link_to 'Sign up', new_user_path, class: 'btn btn-large btn-info'
  - else
    .span6
      .hero-unit.center
        %h2 Me: #{current_user.name}
        %h3
          %b My likes: 
          = current_user.likes
  .span3.offset1
    %h2 Top Ten People On Worth Reading
    %table
      %tr
        %th Name
        %th Likes

      - @users.first(10).each do |user|
        - if current_user != user
          %tr
            %td= user.name
            %td= user.likes

app/views/users/new.html.haml
- provide(:title, 'Sign up now') 
.row
  .span7.offset2
    %h1 Sign up

= render 'form'

.row
  .span8.offset4
    Already a member? Sign in #{link_to 'here', new_session_path}

app/views/users/show.html.haml
- provide(:title, @user.name)
.row
  .span6.offset2
    %p
      %b Name:
      = @user.name
    %p
      %b Email:
      = @user.email_address
    %p
      %b Likes:
      = @user.likes
    %br/
    %p
      %b Subscribers
      %br/
      Subscribers will be listed here...

    %br/
    %p
      %b Emails:
      - if !@emails.empty?
        %table
          %tr
            %th To
            %th Subject
            %th
            %th
          - @emails.each do |email|
            %tr
              %td= email.to
              %td= email.subject
              %td= link_to 'Show', user_email_path(@user, email)
      - else
        No emails yet. Send an email.