config/routes.rb
LikeCounter::Application.routes.draw do
  get "static_pages/about"
  match "/about", to: "static_pages#about"
  get "static_pages/contact"
  match "/contact", to: "static_pages#contact"
  get "static_pages/help"
  match "/help", to: "static_pages#help"
  get "static_pages/home"
  match "whats_this", to: "static_pages#whats_this"
  get "static_pages/whats_this"

  resources :sessions, only: [:new, :create, :destroy]

  resources :emails, only: [:create, :destroy, :index, :show] 

  resources :users do
    resources :emails, only: [:create, :destroy, :index, :show]
    member do
      put 'likes'
      post 'email_likes'
    end
    collection do
    end
  end

  root to: 'users#like_page'
  match '/like', to: 'users#like_page', via: [:get, :post]

  match '/signout', to: 'sessions#destroy', via: :delete

end

app/views/layouts/_footer.html.haml
%footer.footer
  %nav
    %ul.nav
      %li= link_to "About",   about_path
      %li= link_to "Contact", contact_path
      %li= link_to "Help", help_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to "WorthReading", root_path, id: "logo"
      %nav
        %ul.nav.pull-left
          - unless signed_in?
            = form_for(:session, url: sessions_path, html: { class: "navbar-form pull-right" }) do |f|
              = f.text_field :email, placeholder: 'Email', 
                  class: "input-medium sign-in"
              = f.password_field :password, placeholder: 'Password', 
                  class: "input-medium sign-in"
              = f.submit "Sign in", class: "btn-info"
          - else
            %li.divider-vertical
            %li= link_to "Home", root_path
            %li.divider-vertical
            %li#fat-menu.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                #{current_user.name}
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", current_user
                %li= link_to "Mailing List", '#'
                %li= link_to "Account Settings", edit_user_path(current_user.id)
                %li.divider
                %li
                  = link_to "Sign out", signout_path, method: "delete"
            %li.divider-vertical

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= page_title yield(:title)
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render 'layouts/header'

    .container
      .row
        .span6.offset3.center
          - flash.each do |key, val|
            %div{ class: "alert alert-#{key}"}= val
      = yield

      = render 'layouts/footer'
    - if Rails.env.development?
      %br
      %br
      = button_to "Dummy Like Button", 
          email_likes_user_path(id: 2, who_likes: 'jb@gmail.com', email: true) 
      = debug(params)
      = debug(current_user.name) if current_user